#!/usr/bin/env bash
#Loop using whike prints bad luck, good luck and best School

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	fi
done
