#!/usr/bin/env bash
#Loop using whike prints bad luck, good luck and best School

i=0
while [ $i -lt 10 ]
do
        if [ $i -eq 4 ]
        then
                echo "bad luck"
        elif [ $i -eq 8 ]
        then
                echo "good luck"
        else
                echo "Best School"
        fi
        ((i+=1))
done
