#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display hours from 0 to 12

hz=0
while [ $hz -le 12 ]
do
  echo "Hour: $hour"
  min=1
  while [ $min -le 59 ]
  do
    echo "$minute"
    (( min++ ))
  done
  (( hz++ ))
done
